# Generated by Django 6.0.2 on 2026-09-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='participant_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
