ITEMS = [
    {"id": 1, "category": "Tech", "tags": ["hardware", "laptops"], "title": "Foldable laptops go mainstream", "body": "Three major brands ship hinge-screen models this year."},
    {"id": 2, "category": "Tech", "tags": ["ai", "mobile"], "title": "On-device AI cuts cloud costs", "body": "Smaller models are moving inference to the phone itself."},
    {"id": 3, "category": "Tech", "tags": ["delivery", "batteries"], "title": "Battery swaps beat fast charging", "body": "Delivery riders favor 90-second swaps over charge stops."},
    {"id": 4, "category": "Tech", "tags": ["privacy", "browsers"], "title": "Browsers add built-in AI summaries", "body": "Long pages get an on-page summary without leaving the tab."},
    {"id": 5, "category": "Tech", "tags": ["wearables", "health"], "title": "Smart rings track sleep better now", "body": "New sensors cut false readings during light sleep."},
    {"id": 6, "category": "Travel", "tags": ["trains", "budget"], "title": "Slow trains are booking up fast", "body": "Overnight rail routes see a 40% rise in bookings."},
    {"id": 7, "category": "Travel", "tags": ["seasonal", "crowds"], "title": "Shoulder-season trips are trending", "body": "Fewer crowds and lower prices draw budget travelers."},
    {"id": 8, "category": "Travel", "tags": ["cities", "walking"], "title": "Walkable-city guides outsell top-10 lists", "body": "Readers want routes, not rankings, for a new city."},
    {"id": 9, "category": "Travel", "tags": ["solo", "safety"], "title": "Solo travel apps add live check-ins", "body": "Friends get a ping if a planned stop is skipped."},
    {"id": 10, "category": "Travel", "tags": ["luggage", "packing"], "title": "Carry-on-only trips are the new norm", "body": "Airlines' fee hikes push travelers to pack lighter."},
    {"id": 11, "category": "Food", "tags": ["fermentation", "health"], "title": "Fermentation kits sell out again", "body": "Home cooks are chasing the tangy, gut-health trend."},
    {"id": 12, "category": "Food", "tags": ["groceries", "discount"], "title": "Ugly produce boxes go citywide", "body": "Grocers sell surplus fruit at a steep discount."},
    {"id": 13, "category": "Food", "tags": ["meal kits", "waste"], "title": "Meal kits pivot to zero-waste packs", "body": "Portioning is designed around using every last scrap."},
    {"id": 14, "category": "Food", "tags": ["spice", "shelf"], "title": "Small-batch spice blends go direct-to-door", "body": "Farms skip retailers and ship spice packs monthly."},
    {"id": 15, "category": "Food", "tags": ["baking", "gadgets"], "title": "Countertop ovens replace big appliances", "body": "Renters favor compact ovens over full-size ranges."},
    {"id": 16, "category": "Design", "tags": ["layout", "editorial"], "title": "Grid systems make a comeback", "body": "Editorial-style layouts are replacing card-heavy pages."},
    {"id": 17, "category": "Design", "tags": ["typography", "performance"], "title": "Variable fonts save page weight", "body": "One file now covers a whole type family's weights."},
    {"id": 18, "category": "Design", "tags": ["animation", "restraint"], "title": "Motion is used more sparingly now", "body": "Designers trim animation to a single, deliberate moment."},
    {"id": 19, "category": "Design", "tags": ["color", "accessibility"], "title": "Contrast checkers get built into editors", "body": "Designers catch low-contrast text before shipping."},
    {"id": 20, "category": "Design", "tags": ["icons", "systems"], "title": "Icon sets move to a single source file", "body": "Teams generate every size and weight from one master."},
    {"id": 21, "category": "Finance", "tags": ["investing", "apps"], "title": "Micro-investing apps add round-ups", "body": "Spare change from purchases now auto-invests weekly."},
    {"id": 22, "category": "Finance", "tags": ["budgeting", "couples"], "title": "Shared budgeting apps for couples", "body": "Joint expense tracking grows fastest among renters."},
    {"id": 23, "category": "Finance", "tags": ["credit", "students"], "title": "Student credit-builder cards grow up", "body": "Issuers add real rewards once seen only on adult cards."},
    {"id": 24, "category": "Finance", "tags": ["savings", "goals"], "title": "Goal-based savings pots replace one big account", "body": "Users split savings into named, visual buckets."},
    {"id": 25, "category": "Finance", "tags": ["tax", "freelance"], "title": "Freelancers get quarterly tax nudges", "body": "Apps now estimate tax owed after every invoice."},
    {"id": 26, "category": "Health", "tags": ["sleep", "tracking"], "title": "Sleep scores get simpler, not fancier", "body": "Apps trade detailed charts for one plain daily number."},
    {"id": 27, "category": "Health", "tags": ["hydration", "reminders"], "title": "Hydration reminders adjust to weather", "body": "Hot-day alerts now fire more often automatically."},
    {"id": 28, "category": "Health", "tags": ["mental health", "journaling"], "title": "Journaling apps add mood tagging", "body": "One tap logs mood alongside each day's entry."},
    {"id": 29, "category": "Health", "tags": ["fitness", "recovery"], "title": "Recovery days get their own tracking tab", "body": "Apps separate rest metrics from workout streaks."},
    {"id": 30, "category": "Health", "tags": ["nutrition", "labels"], "title": "Scan-a-label apps flag hidden sugar", "body": "A quick camera scan rewrites confusing ingredient lists."},
    {"id": 31, "category": "Education", "tags": ["online courses", "certificates"], "title": "Short certificates outsell full degrees online", "body": "Learners prefer stackable, week-long modules now."},
    {"id": 32, "category": "Education", "tags": ["language", "apps"], "title": "Language apps add real conversation practice", "body": "Users get matched for short voice calls, not just drills."},
    {"id": 33, "category": "Education", "tags": ["kids", "reading"], "title": "Reading apps track comprehension, not just pages", "body": "Quick in-app questions replace end-of-book quizzes."},
    {"id": 34, "category": "Education", "tags": ["study", "focus"], "title": "Focus timers get built into note apps", "body": "Students no longer switch apps to time study blocks."},
    {"id": 35, "category": "Education", "tags": ["exams", "prep"], "title": "Exam prep apps generate practice sets on demand", "body": "Weak topics get more questions automatically."},
    {"id": 36, "category": "Sports", "tags": ["running", "gear"], "title": "Carbon-plate shoes trickle down to beginners", "body": "Cheaper models bring racing tech to everyday runners."},
    {"id": 37, "category": "Sports", "tags": ["cricket", "local"], "title": "Local cricket leagues get live-score apps", "body": "Small-town matches now stream ball-by-ball online."},
    {"id": 38, "category": "Sports", "tags": ["cycling", "safety"], "title": "Bike lights add automatic brake-flash", "body": "Rear lights flash brighter the moment you slow down."},
    {"id": 39, "category": "Sports", "tags": ["fantasy", "apps"], "title": "Fantasy sports apps add injury-risk scores", "body": "Lineups now flag players with rising injury odds."},
    {"id": 40, "category": "Sports", "tags": ["swimming", "gear"], "title": "Smart goggles show pace mid-lap", "body": "Swimmers see split times without stopping at the wall."},
]